---
# tasks file for apache_configuration
#- name: update file
 # lineinfile:
  #  path: "/etc/apache2/sites-available/000-default.conf"
   # state: present
    #regexp: '(.)+DocumentRoot /var/www/html'
    #line: 'DocumentRoot {{ project_directory }}'

- name: Empty the apache conf file 
  copy:
    dest: "/etc/apache2/sites-available/000-default.conf"
    content: ""
    force: yes

- name: Update hosts
  lineinfile:
    path: "/etc/apache2/sites-available/000-default.conf"
    state: present
    line: "{{ item }}"
  with_items:
    - "<VirtualHost *:80>"
    - ""
    - "    ServerAdmin admin@{{ domain_name }}"
    - "    ServerName {{ domain_name }}"
    - "    ServerAlias www.{{ domain_name }}"
    - "    DocumentRoot {{project_directory}}"
    - ""
    -     <FilesMatch \.php$>
    - "        SetHandler \"proxy:unix:/run/php/php{{ php_version }}-fpm.sock|fcgi://localhost/\""
    - "    </FilesMatch>"
    - ""
    - "    ErrorLog ${APACHE_LOG_DIR}/error.log"
    - "    CustomLog ${APACHE_LOG_DIR}/access.log combined"
    - ""
    - "</VirtualHost>"  


- name: Update apache apache2.conf file
  lineinfile:
    path: "/etc/apache2/apache2.conf"
    regexp: "<Directory /var/www/>"
    line: "<Directory {{ project_directory }}>"
- name: Update apache2  envvars file
  lineinfile:
    path: "/etc/apache2/envvars"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {'regexp': "export APACHE_RUN_USER=www-data", 'line': "export APACHE_RUN_USER={{ user_name }}"}
    - {'regexp': "export APACHE_RUN_GROUP=www-data", 'line': "export APACHE_RUN_GROUP={{ user_name }}"}

- name: Enable the Apache2 module proxy_fcgi
  apache2_module:
    state: present
    name: proxy_fcgi

- name: Enable the Apache2 module setenvif
  apache2_module:
    state: present
    name: setenvif

- name: Enabling conf
  command: "a2enconf php{{ php_version }}-fpm" 

- name:
  service:
    name: apache2
    state: restarted
