---
- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: execute composer install script
  command: php /tmp/composer-setup.php
  args:
    chdir: /tmp

- name: Copy files from composer.phar
  copy: 
    remote_src: True 
    src: /tmp/composer.phar 
    dest: /usr/local/bin/composer
    mode: +x

#- name: -----------------------File and Directory Permission------------------------------------------
 # file:
 #   path: "/home/{{ user_name }}"
 #   owner: "{{ user_name }}"
 #   group: "{{ user_name }}"
 #   recurse: yes
 #   mode: 0777


- name: Set Magento Access Keys for Composer
  command: composer global config  http-basic.repo.magento.com "{{ magento_username }}" "{{ magento_password }}"
  become: yes
  environment:
    COMPOSER_ALLOW_SUPERUSER: 1


- name: Install magento on directory
  command: composer create-project --repository=https://repo.magento.com/ magento/project-community-edition "{{ project_directory}}"
  become: yes
  environment:
    COMPOSER_ALLOW_SUPERUSER: 1

- name: ----Change File owner---------------
  file:
    path: "{{ project_directory }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    recurse: yes
    #mode: 0700

- name: -----Make Executeable file of magento----------------
  file:
    path: "{{ project_directory }}/bin/magento"
    mode: u+x



- name: Set Files Permissions to g+w
  shell: |
        find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} +
        find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} +
  args:
    chdir: "{{ project_directory }}"

#- name: -----------------------File and Directory Permission------------------------------------------
#  file:
#    path: "/home/{{ user_name }}"
#    owner: "{{ user_name }}"
#    group: "{{ user_name }}"
#    recurse: yes
#    mode: 0700



#- name: file and direcotry permssion 
#  file:
#    path: "{{ project_directory }}"
#    owner: "{{ user_name }}"
#    group: "{{ user_name }}"
#    recurse: yes
#    mode: 0775

- name: Configure magento main configuration
  shell: |
        bin/magento setup:install \
         --base-url=http://"{{ domain_name }}" \
         --db-host=localhost \
         --db-name="{{ db_name }}" \
         --db-user="{{ db_user }}" \
         --db-password={{ db_pass }} \
         --admin-firstname=Admin \
         --admin-lastname=User \
         --admin-email=admin@"{{ domain_name }}" \
         --admin-user=admin \
         --admin-password=admin123 \
         --language=en_US \
         --currency=USD \
         --timezone=America/Chicago \
         --use-rewrites=1
  args:
    chdir: "{{ project_directory }}"


#- name: change file and direcotry permssion
#  file:
#    path: "{{ project_directory }}"
#    owner: "{{ user_name }}"
#    group: "{{ user_name }}"
#    recurse: yes
#    mode: 0700


- name: Disable Two factor authentication , clear cache and di compile
  shell: |
        bin/magento module:disable Magento_AdminAdobeImsTwoFactorAuth Magento_TwoFactorAuth
        bin/magento cache:flush
        bin/magento setup:di:compile
  args:
    chdir: "{{ project_directory }}"
