---
- name: Test Project Directory
  hosts: all
  vars:
    user_name: wp_user
    user_pass: 123456789
#node var
    Home_path: "/home/{{ user_name }}"
    project_dir_name: node_project
    node_project_directory: "{{ Home_path}}/{{ project_dir_name}}"
    node_version: 20.14.0
    repo_url: https://github.com/kinsta/hello-world-nodejs.git
  become: true
  roles:
#    - basic_config
#    - nvm_installer
    - node_configuration
