---
- name: Docker installer
  hosts: all
  vars:
    docker_version: 13
  tasks:

  - name: get os release code
    command: "lsb_release -c"
    register: os_result

  - ansible.builtin.set_fact:
      os_version_code: "{{ os_result.stdout.split()[1] }}"

  - name: Debug value
    debug:
      msg: "{{ os_version_code }}"

  - name: Creates directory
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: 0755
    become: True
 
  - name: Add docker GPG key
    ansible.builtin.get_url:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      dest: "/etc/apt/keyrings/docker.asc"
      mode: '0644'
      force: true
    become: True

 
  - name: Add Docker repository
    lineinfile: 
      line: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{os_version_code }} stable"
      dest: /etc/apt/sources.list.d/docker.list
      state: present
      create: yes
    become: true

  - name: Update all packages to their latest version
    apt:
      update_cache: yes
    become: True

  - name: Install Docker all packages
    apt:
      name: "{{ item }}"
      state: present
    loop:
       - docker-ce 
       - docker-ce-cli 
       - containerd.io
       - docker-buildx-plugin 
       - docker-compose-plugin
       - docker-compose
    become: True

  - name: Start Docker
    service:
      state: started
      daemon_reload: true
      name: docker
      enabled: yes
    become: true

  - name: Add user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes
    become: true

  - name: Restart Docker Service
    service:
      state: restarted
      name: docker
    become: true
