---
# tasks file for project_directory_setup
- name: Create a project directory setup
  file:
    path: "{{ project_directory }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
    mode: '0700'


