---
- name: Test Project Directory
  hosts: all
  vars:
    user_name: 
    user_pass: 5
    php_version: 8.3
    php_fpm_conf_file_path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    db_user: wp-user
    db_pass: S350v+t37t3v1wcWMp0g
    db_name: wp_db
    mysql_root_password: S350v+t37t3v1wc
    project_directory_name: wordpress
    project_directory: "/home/{{ user_name }}/{{ project_directory_name }}"
    domain_name: markhorwear.com
    web_port: 80
  become: true
  roles:
    - basic_config
    #- apache_and_php_setup
    #- apache_configuration
    #- project_directory_setup
    #- mysql_setup
    #- wordpress_setup
