---
- name: Test Project Directory
  hosts: all
  vars:
    user_name: wp_user
    user_pass: 
    php_version: 8.2
    php_fpm_conf_file_path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    db_user: wp-user
    db_pass: S3
    db_name: wp_db
    mysql_root_password: S3
    project_directory_name: wordpress
    project_directory: "/home/{{ user_name }}/{{ project_directory_name }}"
    domain_name: example.com
    web_port: 80
  become: true
  roles:
    - basic_config
    - apache_and_php_setup
    - apache_configuration
    - project_directory_setup
    - mysql_setup
    - wordpress_setup
